"use client";

import Link from "next/link";
import { CheckCircle } from "lucide-react";

export default function PaymentSuccessEN() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-gray-50 px-4">
      <div className="bg-white rounded-2xl shadow-lg p-8 text-center max-w-md">
        <CheckCircle className="mx-auto text-green-600" size={72} />
        <h1 className="text-2xl font-bold text-[#0A2942] mt-4 mb-3">
          Payment confirmed ✅
        </h1>
        <p className="text-gray-700 mb-6">
          Thank you for your trust.<br />
          Your contract and invoice have been sent to your email address.
        </p>

        <Link
          href="/my-space"
          className="inline-block bg-[#0A2942] text-white py-2 px-6 rounded-lg hover:bg-[#103d66] transition"
        >
          Back to my account
        </Link>

        <p className="text-xs text-gray-500 mt-6">
          A digital copy of your contract and invoice has been automatically generated by the ITERIUM PARTNERS platform.
        </p>
      </div>
    </main>
  );
}